# 基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'
# repo = 'tomasr/molokai'
# ステータスバー
repo = 'itchyny/lightline.vim'

[[plugins]] # コメントON/OFFを手軽に実行
repo = 'tomtom/tcomment_vim'

[[plugins]] # カラースキーマ
repo = 'tomasr/molokai'

[[plugins]] # indent guides
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup=1
  let g:indent_guides_start_level=2
  let g:indent_guides_auto_colors=0
  autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=022
  autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=027
  let g:indent_guides_color_change_percent = 30
  let g:indent_guides_guide_size = 1
'''

[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'


