
# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# 成形のためにシングルスペースの有無
SingleBeforeFirstArg:
  Enabled: false

# トップレベルにあるコメントの有無
Style/Documentation:
  Enabled: false

# 複数行での「lambda」で「->」による省略記法を許可
Lambda:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# メソッド名のprefixに「set_」「get_」を許可
AccessorMethodName:
  Enabled: false

# クラスにコメントを残さない
Documentation:
  Enabled: false

StringLiterals:
  EnforcedStyle: single_quotes
FormatString:
  EnforcedStyle: percent
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Layout/MultilineBlockLayout:
  Enabled: false
