#!/bin/sh

ln -sf $(pwd)/.tmux.conf $HOME/.tmux.conf
ln -sf $(pwd)/.gitconfig $HOME/.gitconfig

mkdir -p $HOME/.config
ln -sf $(pwd)/karabiner $HOME/.config/karabiner
ln -sf $(pwd)/peco $HOME/.config/peco
ln -sf $(pwd)/.zshrc $HOME/.zshrc
ln -sf $(pwd)/.zshrc.base $HOME/.zshrc.base
ln -sf $(pwd)/.zshrc.peco $HOME/.zshrc.peco
ln -sf $(pwd)/.zshrc.alias $HOME/.zshrc.alias
ln -sf $(pwd)/.zshrc.path $HOME/.zshrc.path
ln -sf $(pwd)/.Brewfile $HOME/.Brewfile

