twitter_api:
  consumer_key:        "Eo1IBGNh94daqxf0DfZvCcThy"
  consumer_secret:     "zRHjNvkGpfNdPTLVFKWHjg90Sf24gcYKDvX7M2Tr3IYKTm7cWW"
  access_token:        "538181797-NTx9gWM1hY06tXGfvS6Qrswa8yXuM0TMOHjstkQr"
  access_token_secret: "NkSOMbp2wP2IzyrK2YSlanHiC7wVgWyZ7OAPKIt59FLGY"
editer: "vim"
