[[plugins]]
repo = 'Shougo/dein.vim'

# ステータスバー
[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]] # コメントON/OFFを手軽に実行
repo = 'tomtom/tcomment_vim'

[[plugins]] # 補完
repo = 'tpope/vim-surround'

[[plugins]] # indent guides
repo = 'Yggdroot/indentLine'

[[plugins]] # 色のプレビュー
repo = 'lilydjwg/colorizer'

[[plugins]] # 自動で閉じる
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'jdkanani/vim-material-theme'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]] #  Git 差分とか
repo = 'tpope/vim-fugitive'
[[plugins]] #  Git 差分とか
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'neomake/neomake'
hook_add = '''
autocmd! BufWritePost * Neomake
'''

# Window Resize
[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
let g:winresizer_vert_resize=3
let g:winresizer_horiz_resize=1
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
[[plugins]]
repo = 'fishbullet/deoplete-ruby'

[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'vim-scripts/vim-auto-save'
hook_add = '''
let g:auto_save = 1
'''

