[[plugins]]
repo = 'Shougo/dein.vim'

# ステータスバー
[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]] # コメントON/OFFを手軽に実行
repo = 'tomtom/tcomment_vim'

[[plugins]] # 補完
repo = 'tpope/vim-surround'

[[plugins]] # indent guides
repo = 'Yggdroot/indentLine'

[[plugins]] # 色のプレビュー
repo = 'lilydjwg/colorizer'

[[plugins]] # 自動で閉じる
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'jdkanani/vim-material-theme'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'atelierbram/vim-colors_duotones'

[[plugins]]
repo = 'vim-scripts/ChocolateLiquor'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'vim-scripts/sudo.vim'

[[plugins]] #  Git 差分とか
repo = 'tpope/vim-fugitive'
[[plugins]] #  Git 差分とか
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'neomake/neomake'
hook_add = '''
autocmd! BufWritePost * Neomake
let g:neomake_javascript_enabled_makers = ['eslint']
let g:neomake_ruby_enabled_makers = ['mri','rubocop']
let g:neomake_haskell_enabled_makers = ['ghcmod', 'hlint' ]
let g:neomake_typescript_enabled_makers = ['tslint']

augroup my_neomake_signs
    au!
    autocmd ColorScheme *
        \ hi NeomakeErrorSign ctermfg=white |
        \ hi NeomakeWarningSign ctermfg=yellow
augroup END
'''

# Window Resize
[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
let g:winresizer_vert_resize=3
let g:winresizer_horiz_resize=1
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'


[[plugins]]
repo = 'rhysd/clever-f.vim'

# [[plugins]]
# repo = 'vim-scripts/vim-auto-save'
# hook_add = '''
# let g:auto_save = 1
# '''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = "Shougo/context_filetype.vim"

[[plugins]]
repo = 'thinca/vim-template'
hook_add = '''
let g:template_basedir = '~/.config/nvim'
let g:template_free_pattern = 'templates'
'''

[[plugins]]
repo='yuratomo/w3m.vim'
hook_add = '''
let g:w3m#command = 'w3m'
'''
