# 特定のファイルタイプで読み込む
[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
# repo = 'itmammoth/run-rspec.vim'
repo = 'meriy100/run-rspec.vim'
on_ft= ['ruby']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'jason0x43/vim-js-indent'
on_ft = ['typescript']
hook_add = '''
let g:js_indent_typescript = 1
'''

[[plugins]]
repo = 'mhartington/nvim-typescript'
on_ft = ['typescript']
hook_add = '''
let g:deoplete#enable_at_startup = 1
'''

[[plugins]] # Swift のハイライト
repo = "kballard/vim-swift"
on_ft = ['swift']

[[plugins]] # coffee のハイライト
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]] # slim のハイライト
repo = "slim-template/vim-slim"
on_ft = ['slim']

[[plugins]]
repo = 'dag/vim2hs'
on_ft = ['haskell']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']
hook_add = '''
let g:vim_markdown_autowrite = 0
'''

[[plugins]]
repo = 'vim-latex/vim-latex'
on_ft = ['latex']

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'jsx']
[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['javascript', 'jsx']
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'jsx']

[[plugins]]
repo   = 'Shougo/unite.vim'
on_cmd = ["Unite"]

# unite.vim を読み込んだら一緒に読み込む
[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo =  'scrooloose/nerdtree'
on_source = ['unite.vim']

# 特定のコマンドを打ったら読み込む
[[plugins]]
repo      = 'thinca/vim-prettyprint'
on_cmd    = ['PP', 'PrettyPrint']


[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'moznion/hateblo.vim'
on_source = ['webapi-vim']

[[plugins]]
repo = 'ujihisa/neco-ghc'
on_ft = ['haskell']
hook_add = '''
let g:necoghc_enable_detailed_browse = 1
autocmd FileType haskell setlocal omnifunc=necoghc#omnifunc
'''
